### PR TITLE
batchable getRandomNumberFromRange invocable

### PR DESCRIPTION
**Pull request by mtptb**
Hi @alexed1 ,

I've provided an improvement about batchable GetRandomFlowAction.
Can you evaluate and merge it?

Thanks

### CODE REVIEW

**Review by alexed1 — APPROVED** [review]
Thanks for this improvement, Matteo, and welcome to the repo! There are still some 'early' actions I built where I took that shortcut. I'm glad you made this properly bulkified.

**Comment by alexed1** [comment]
I got this test failure when I tried to package your change. It's quite possible that the test failure has nothing to do with your code. However, it would be great if you have a chance to look into it. Are you able to run that test successfully? 

Version create.... Create version status: Error
Error (1): Multiple errors occurred: 
(1) Apex Test Failure: Class.GetRandomNumberTest.numberAboveOneGeneratedIsInRange: line 49, column 1 System.AssertException: Assertion Failed: Expected: true, Actual: false

**Comment by mtptb** [comment]
Hi Alex,

sure, I can check it quickly and back to you.

**Comment by mtptb** [comment]
> I got this test failure when I tried to package your change. It's quite possible that the test failure has nothing to do with your code. However, it would be great if you have a chance to look into it. Are you able to run that test successfully? 
> 
> 
> 
> Version create.... Create version status: Error
> 
> Error (1): Multiple errors occurred: 
> 
> (1) Apex Test Failure: Class.GetRandomNumberTest.numberAboveOneGeneratedIsInRange: line 49, column 1 System.AssertException: Assertion Failed: Expected: true, Actual: false
---
Hi Alex,

sure, I can check it quickly and back to you.

**Pull request merged**
