### PR TITLE
Bypass Community Sharing Rules

### PR DESCRIPTION
**Pull request by rygramer**
hey @jdayment - one of the other feature requests i saw was for the ability for community users to upload files to records that they don't necessarily have access to. take a look at this. let me know if you'd like a video explanation of what's going on.

### CODE REVIEW

**Comment by jdayment** [comment]
@rygramer I should be able to take a look this afternoon

**Comment by rygramer** [comment]
@jdayment here's the writeup: https://docs.google.com/document/d/1mgaUmHNb098e0btaQOESF8u4IZjn7TTGx4PCwTz-00k/edit?usp=sharing

I combined the functionality from this PR with the previously merged PR in the documentation. So if we find issues with the code here, I can modify the writeup to remove the Bypass Community Sharing Rules documentation if we want to get the other stuff out the door while we refine.

**Comment by jdayment** [comment]
@rygramer This is really great work! @alexed1 I deployed to my org and everything is working great.

**Comment by rygramer** [comment]
Thx @jdayment, glad I found some time to focus on learning LWC. They are addicting for sure.

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
Here's version 1.3 that includes these improvements: https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G000003rUb5QAE

test it out if you get the chance.

**Comment by alexed1** [comment]
Ryan, this is great work...you added a lot of immediately useful and tangible improvements. If you're interested and want to provide your email, I'll invite you to the Flow Developer slack workspace

**Comment by rygramer** [comment]
Thanks @alexed1! Yes, definitely would love in the slack invite - ryangmercer@gmail.com

I did find an issue when I was upgrading the package. I'll open another PR to fix it.

**Comment by alexed1** [comment]
here's version 1.3.1  with that fix https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G000003rUbAQAU

**Comment by rygramer** [comment]
the new version has passed all of my testing. i made the final adjustments to the announcement write up. @jdayment - do you want me to write the update for the main post [https://unofficialsf.com/from-josh-dayment-improved-file-upload-in-flow-screens/]?

**Comment by jdayment** [comment]
That would be awesome

**Comment by rygramer** [comment]
How's this? Tracked changes so you can see before vs after, feel free to edit my revisions at will.
https://docs.google.com/document/d/1mgaUmHNb098e0btaQOESF8u4IZjn7TTGx4PCwTz-00k/edit#heading=h.q26153j7xyko

**Pull request merged**
