### PR TITLE
sendBetterEmail - Code refactoring and optimization

### PR DESCRIPTION
**Pull request by msrivastav13**
@jdpond @alexed1 I have started the work on code splitting and optimization.

I am yet to bulkify task creation logic and create a separate component that uses the same controller logic but can accept 1000s of requests for Email Sent. 

I wanted to get this PR in there so if there are concerns lets raise it now. Also helps early testing it if anybody wants to push to make sure nothing is broken.

Do not merge it yet until I complete rest of the work.

### CODE REVIEW

**Comment by jdpond** [comment]
Mohith, this is fantastic work! I set up and ran tests last night, and other than the known CPE bugs, this looks good.  I still need to run 3 more examples, but so far - GREAT!!!!

Couple of minor observations which may not require correction:

1. When using TEST_WITH_CREATED_RECORDS = false;, coverage on AddTasksToEmail drops to 67%
2. The additional classes have very common names and may cause conflict in orgs.  The changes add the following classes:
	a. Request
	b. AddAttachmentToEmail
	c. Response
	d. Constant

**Coverage**
Until we move to managed packages and/or namespaces, AddTasksToEmail will cause install fail.  One mechanism for increasing coverage is the isRunningTest() capability.  In previous versions, if it was in a test (and ONLY if it was in a test), it looked to see if the failure reason was an invalid RecordId type (User).  If so, it ignored the error and allowed addTasks to be run.  This tested the functionality, even though it failed and provided the needed coverage (90%).

This technique allowed the deployment as unmanaged package.

**ORG Class Naming Conflicts**
I have the same problem with CPE.  What do you think about adopting a strategy much as FBC did - preceeding the class names with a unique identifier.   Example:
	a. sbe_Request.cls
	b. sbe_AddAttachmentToEmail
	c. sbe_Response
	d. sbe_Constant

I also need to change LWC names:
	a. sbe_addNewMembers
	b. sbe_ucModal

**Test Coverage Results**
=== Apex Code Coverage
ID                  NAME                  % COVERED           UNCOVERED LINES
──────────────────  ────────────────────  ──────────────────  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
01p56000004qymJAAQ  SendBetterEmail       90%                 119,153,154,155,214,215,230,257,279,399,439,441,442,443,444,467,469,471,472,473,474,475,493,495,496,497,498,514,515
01p560000055BCwAAM  AddAttachmentToEmail  100%
01p560000055BDGAA2  Response              NaN%
01p560000055BD6AAM  Constant              100%
01p560000055BDBAA2  Request               NaN%
01p560000055BDLAA2  SendEmailUtil         80%                 37,38,39,40,41,43,69,70,71,72,73,75,121,122,173,183,190,193,194,195,196,197,198,199,200,201,203
01p560000055BDQAA2  AddTasksToEmail       67.14285714285714%  16,17,19,29,30,34,36,41,47,49,50,51,52,53,54,55,56,57,58,59,65,69,92

**Comment by msrivastav13** [comment]
@jdpond Great points on namespace collision. I think yes, it's better we add a prefix to all classes to be safe. I suggest we keep it in capitals for apex class like below to some of these.

a. SBE_Request.cls
b. SBE_AddAttachmentToEmail.cls
c. SBE_Response.cls
d. SBE_Constant.cls

LWC names can be like below

a. sbe_addNewMembers
b. sbe_ucModal

I plan to spend some time on the test code coverage after I fix the task bulkification issues.

**Comment by msrivastav13** [comment]
@jdpond I will rename the classes in the next iteration as per above!

**Comment by jdpond** [comment]
Re Bulkification of the sendEmail method
How would sendBetterEmail be used if:
1.	I want to send 1-10 emails by passing in a single string address or a collection
2.	I want to send 100 emails
3.	I want to send 500 emails
4.	I want to send 5000 emails

These questions raised some background technical information that might be useful in refactoring, and bulkifying – most of it is copied directly from the messaging documentation.  The attached spreadsheet also has much of the document-derived descriptions – as well as a way to filter by environment.
________________________________________
1.	sendEmail(emails, allOrNothing) Sends the list of emails instantiated with EITHER SingleEmailMessage OR MassEmailMessage
2.	For SingleEmail, the maximum size for this field is 4,000 bytes. The maximum total of toAddresses, ccAddresses, and bccAddresses per email is 150. All recipients in these three fields count against the limit for email sent using Apex or the API.
3.	Maximum collection size of  Messaging.sendEmail requests per method execution :== 10
4.	Count of  Messaging.SendEmailResult per Messaging.sendEmail collection member :== 1 (NOT 1 PER OBJECT OR RECIPIENT)  Each Apex invocation can include 10 total calls to the sendEmail method.  This means (barring conflict with other limits), a single flow path can execute 10 sendEmails each having 10 email Requests, total of 100 requests.
5.	each sendEmail(emails, allOrNothing) can execute maximum 10 SingleEmailMessage OR MassEmailMessage requests (must be of same type).
6.	Maximum TargetId per singleEmail :== 1
7.	Maximum TargetIds per massEmail :== WhatIds, but can only be Contract, Case, Opportunity, Product.  The objects must be of the same type and other "to" address types not allowed
8.	Number of SendEmailResult per Messaging.sendEmail collection items (limit 10) :==1 for a maximum of 10 if 10 requests are issued concurrently
9.	Number of unique TemplateIds allowed per sendEmail(emails, allOrNothing) :== same as collection size - maximum of 10, but each request in the collection can be unique.
10.	Number of unique WhatId/Record types allowed per sendEmail(emails, allOrNothing)  :== same as collection size - maximum of 10, but each request in the collection can be unique.
11.	The limit on number of recipients in singleEmail :== 150 (including to, cc, bcc)  - limit of singleEmail, so in theory, a bulked 10 requests would be  1,500 per invocation
12.	If you use singleEmail or massEmail, the limits per request are more likely to be reached if you are using saveAsTask because of the limit on the number of updates/inserts you can do on records (150 - 4, see below).
13.	I have no idea how many DML calls are intrinsic to each request of (sendEmail(emails, allOrNothing) other than below, sendBetterEmail has no other DML calls, but (for example), sendEmail may cost a DML per recipient if saveAsActivity:==true.
14.	
________________________________________
Bulkification in sendBetterEmail - status quo:
1.	Maximum Number of "queries" per collection Item Email Request = 5 (note, these only apply if saveAsTask :== true, used to do it by default if saveAsActivity :== true or unspecified)
a.	getSObjectType().getDescribe().getName() to determine if "User" (but ONLY if test.isRunningTest())
b.	FROM EmailTemplate WHERE Id=:request.templateID (each request may have a unique templateID)
c.	getSObjectType().getDescribe().getName() to determine Target Object Type (each request may have a different Target Object Type)
d.	Select Name From . . .  Where In {recipients list} to get recipient names for Subject of task (each request may have a different Target Object Type)
e.	Insert (for all tasks) (each request may have a different Target Object Type)
2.	Each of these occur once, and only once inside the "for" loop.  The for loop is for each SendEmailResult (maximum of 10, if 10 bulked and each occurs because it has conditions which may be unique to each request.
3.	In theory, if you specified saveAsTask, each invocation of sendBetterEmail could initiate a maximum of 50 Queries in a Test Class Bulk Test, 40 Queries in production system bulk of 10 - and the maximum bulk size is 10 (sendEmail(emails, allOrNothing) limit)

**Comment by alexed1** [comment]
great point about the potential conflict for class names like Request. I'd suggest though that we not use the prefix form because it has namespace roots. Instead, add text to the name: SendBetterEmailRequest and SendBetterEmailResponse

**Comment by msrivastav13** [comment]
I like making it SendBetterEmail for all the classes. That's better than a namespace prefix. Also, the other thing about the unlocked package is you can namespace them as well. However, having built number of apps for app exchange I would like to avoid getting into namespace thing if possible. Especially with issues, I have seen in the past.

I will change it to SendBetterEmail for those code components.

**Comment by msrivastav13** [comment]
@alexed1 and @jdpond Fixed the names as suggested by Alex!

**Comment by jdpond** [comment]
Hold on for about an hour and let me drop the CPE name changes too?

**Comment by jdpond** [comment]
@msrivastav13  I'd like to add the CPE name changes into yours and use it as the current code base to debug two know issues with CPE. @alexed1

**Comment by msrivastav13** [comment]
@jdpond I made the PR available to merge if you like! Hope it helps. I tested the tests run and looked good.

I will add more test code later and refactor the Task creation logic as well and create the bulk email flow component.

Good luck with CPE.

**Comment by jdpond** [comment]
@msrivastav13 I merged https://github.com/msrivastav13/LightningFlowComponents into https://github.com/jdpond/LightningFlowComponents  made the name changes and committed.  You may want to merge then add the commit to this pull.  I am using the new as the code base.

**Comment by msrivastav13** [comment]
@jdpond Have merged from your branch and this has your changes as well.

Note I will be working now only by Friday on this to complete the rest of the work. Very close to getting a really good code!

**Comment by msrivastav13** [comment]
@jdpond bulkified task inserts as well. Should address #454 completely. Please test and let me know if you see anything weird. The code coverage in my scratch org is 88%

Screen Shot 2020-08-30 at 1 37 46 AM

**Comment by alexed1** [comment]
I'm going to go ahead and merge this code and create a package for testing.

**Pull request merged**
