### PR TITLE
bulkify SendHTMLEmail component

### PR DESCRIPTION
**Pull request by msrivastav13**
The state of the component

1. It is not bulkified and can easily fail with records with 10 records
2. The SendEmail is inside the loop
3. The Queries are inside the loop
4. The DML is inside the loop
5. Unnecessary queries and queries are repeated.

The PR fixes the above and also makes method names with small letters!

### CODE REVIEW

**Comment by alexed1** [comment]
@msrivastav13   thank you very much for the code improvements!

@jdpond , I know you're close to a big checkin on this component to introduce a custom property editor. If you're ready to go, then perhaps we should get that in and then have Mohith see which parts of his code are complementary

**Comment by jdpond** [comment]
@msrivastav13 I think I got these with what amounted to a complete rewrite for 1.33.2, but could you check for me?  The fixes would be visible in https://github.com/jdpond/LightningFlowComponents/tree/sendHTMLEmailV1_33_2/flow_action_components/SendHTMLEmail
Package: https://login.salesforce.com/packaging/installPackage.apexp?p0=04t3h0000045qdRAAQ

**Comment by jdpond** [comment]
@msrivastav13 - a little history and an apology.  When we added the massEmail, separation of activity and task, as well as several other enhancements, we came to the conclusion that the component was virtually unusable because of the complexity of the parameters.  The delay in the release has been to for Summer '20 compatibility and the release of Flow Base Components, as well as some debugging of the flow combo boxes.   I'd really appreciate if you could take a look and see if we got all of your enhancements and thank you so much for adding more eyes and resources to this component!

**Comment by msrivastav13** [comment]
@jdpond Please find my review comments

**Performance Impacts**

- **Bulkify SOQL**. Please look into my PR that shows how one can use Maps and Sets to make the sure query is done only once than executing SOQL in the loop. If you do not do this moment someone uses your component with 50 records they will hit this limit. Note this is definitely not desirable. This component should be able to work easily till it hits heap says like at least 1000 records!

Pay attention to queries on the ContentVersion record query (`addAttachment` ) and queries on the email template. Make sure we use Maps and Sets and take the query out of the loop.

Query on LanguageLocaleKey should be done only once. It's in the loop today.

- **Bulkify DML** Please look into the `createActivity` method and move the insert of Task to a list and do not insert it in loop. The component will hit an error with 100 records (probably even less).

All queries and DML should move outside the loop.

**General Code Improvements**

- please use brackets for `if` loop, its hard to read code without appropriate brackets.

- Method names  starting with a small letter

- If a method is going above 50 lines we ideally break down into multiple smaller Methods, improves readability.

@jdpond Its learning and we will get there together :). I just want to make sure we give community best code possible that not works but is scalably usable for a lot of use cases :)

Let me know if you need me to refactor, I am open to that. For that, you will get the changes in and I will work on refactor, or if you want to learn my PR is here so you can make changes and submit a PR.

**Comment by jdpond** [comment]
Thanks @msrivastav13.  Please refer to #351 as to why some of the issues you mentioned above are within loops (e.g., build each message independently then send.  The loop is based on using multiple message sends - which is not the common use of CPE, and would require an outside invocation.  As with most "run on" systems, this development was done based on legacy code and it could definitely more properly be refactored for readability and maintainability.  As one of the original developer of Unix, with root access to linux Kernel dev, and one of the original 7 developers of mediawiki, I definitely value your input and would appreciate your taking these tasks on.  My role has been to get to a deliverable product within a changing infrastructure and I'm sure aesthetics would be greatly valued from here on - thank you for your learned advice and I hope you can correct these issues.

**Comment by msrivastav13** [comment]
@alexed1 let's merge the changes from @jdpond and then I can work on layering all the work I did to bulkify and make the code efficient!

Hope that works for everyone 🙏

@jdpond thank you for work on this component and contributions! Love the community and openness here! Also huge respect for the work!

**Comment by jdpond** [comment]
Udaman.   My personal contact is jack.pond@psitex.com.  I was sooooooo embarrassed at the quality of the code released, but decided "Perfect is the enemy of the good." --  Voltaire[Francois-Marie Arouet](1694-1778).   I have about a thousand ideas on how to clean this up and can give you some good starting points.

**Comment by msrivastav13** [comment]
@jdpond thank you will reach out and also will tag you! Hopefully we get your code merged so I can work on it!

**Comment by alexed1** [comment]
Jack's code is merged into master now, so go ahead Mohith.

Jack, you've added tremendous value to this action. Don't beat yourself up about code quality. It's a journey!

**Pull request closed without merging**
