### PR TITLE
Trim spaces from split csv string

### PR DESCRIPTION
**Pull request by Tamarer**

### CODE REVIEW

**Comment by alexed1** [comment]
Let me know if you'd like to reopen and discuss this one, @Tamarer.

**Comment by Tamarer** [comment]
@alexed1  can you please explain why this update can’t be merged. I may have misunderstood If I had some additional tasks here, thanks!

**Comment by alexed1** [comment]
I don't think the code you're proposing here will work because I don't think you can directly access csvString.

**Comment by Tamarer** [comment]
I think I can access csvString because it’s declared in line 9 but for some reason this update doesn’t actually trim the spaces.
Thank you for your help, you can delete this branch.

**Pull request closed without merging**
