### PR TITLE
fix for issue 883 & 890

### PR DESCRIPTION
**Pull request by JerrycsPoon**
https://github.com/alexed1/LightningFlowComponents/issues/883

### CODE REVIEW

**Comment by alexed1** [comment]
Looks useful! @ericrsmith35 to review

**Comment by ericrsmith35** [comment]
I will be following up on this.

**Comment by JerrycsPoon** [comment]
Added fix on issue #890, but tinkering the css file

**Comment by ericrsmith35** [comment]
These changes will be incorporated in v3.3.3 to be released with Winter '22

**Pull request closed without merging**
