### PR TITLE
Update Flow Flexcard Action List to use lightning-flow

### PR DESCRIPTION
**Pull request by jdayment**
update fsc_actionList to utilize lightning-flow from Winter 23 to launch subflow from Flow Flex Card

### CODE REVIEW

**Comment by jdayment** [comment]
I also have a post ready to go about the reason for the change and the positive impact having the native lightning-flow functionality in LWC

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
Getting this on build: fsc_flexcardFlow: No MODULE named markup://lightning:flow found : [markup://c:fsc_flexcardFlow, markup://c:fsc_actionList3]

**Comment by jdayment** [comment]
Is the packaging org on Winter 23 yet?

**Comment by RebbePod** [comment]
Is there an option to hide the list or menu, so one can utilize the full real estate of the card?

**Comment by jdayment** [comment]
@RebbePod if you do not enter any flows in the flow/actions input of the CPE the list and menu will not populate and the content will span the screen for fields they are still single column though so no side-by-side fields. One of the latest releases also included scrolling to the cards as well so it does not bleed over. In GitHub it's easier to get help or add a feature request from the [issues tab](https://github.com/alexed1/LightningFlowComponents/issues) pull requests are where we manage getting our code into the repo and packages :)

**Comment by RebbePod** [comment]
@jdayment Thank you, I'm not seeing that functionality, is it part of screen components 3.0.14? (3.0.15 has bugs)

**Pull request merged**
