### PR TITLE
Update FieldPickerController to API 59

### PR DESCRIPTION
**Pull request by jdayment**
Updates to API 59 to support new core Non-Profit  cloud objects

### CODE REVIEW

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
should I repackage for this? Does it facilitate anything immediately?

**Comment by ericrsmith35** [comment]
We have a few updates now for the FlowScreenComponentsBasePack that should
warrant a new version.

**Comment by jdayment** [comment]
What Eric said 😅this was feedback from someone using the new Non-Profit
cloud some objects were missing

**Comment by jdayment** [comment]
@alexed1 Can you also do a new version of FlowActionsBasePack this should be part of that package

**Pull request merged**
