### PR TITLE
DualListBox - Added new param "Select All" to have a user select all of the availab…

### PR DESCRIPTION
**Pull request by spider-bkv**
Hi all,

Added new param "Select All" to have a user select all of the available options. Params "Min" and "Max" will be ignored.

I found it useful for others.

Thank you!

### CODE REVIEW

**Comment by ericrsmith35** [comment]
Are you looking to offer a Select All option to the user running the flow or are you looking to add a validation that requires the user to select every option?

**Comment by alexed1** [comment]
Thanks for the enhancement, Kirill!

What's your favorite example use case where the user would be asked to select everything?

**Comment by spider-bkv** [comment]
> Thanks for the enhancement, Kirill!
> 
> What's your favorite example use case where the user would be asked to select everything?

Thank you for the question @alexed1 !

So, the common use case description is "prioritization of a list of items" and when it's mandatory to use all of the items it's good to have the "Required to select all" parameter, instead of putting vars to Min and Max (btw, it's not possible now, also).

The most recent request I got was asking the user to prioritize a list of apartment properties (ie Floor Space, Light/Views, Closet Space, Unique Layout). After about a year in production, we've got good results from the users, it was clear to them what to do with the DualListBox moving items one-by-one from left to right in the highest-lowest order and having the ability to move them upside-down when they moved them to the right.

Thank you.

**Comment by alexed1** [comment]
Got it... ok, I'd like to propose a few small tweaks:
1) move your checkbox from above the Min and Max to below. That will make it clearer that Min and Max are not dependent on the setting of the checkbox.
2) change the text to 'All items must be selected (use for sorting applications)'

**Comment by alexed1** [comment]
Just checking in here, @spider-bkv . Do you think those tweaks would be possible?

**Comment by alexed1** [comment]
Closing for now, but happy to reengage on this.

**Pull request closed without merging**
