### PR TITLE
Updates Generate Collection Report to use Field Label instead of API Name

### PR DESCRIPTION
**Pull request by jmdohn**
As a consumer of the emails, it would be best to display the field label so that I can understand what fields correspond to the record in Salesforce.

image

### CODE REVIEW

**Comment by danifin** [comment]
@jmdohn it's a great addition, can you add an option to display lookup field names instead of the Id?

**Comment by alexed1** [comment]
Hey, thanks for this enhancement! Let me make sure I understand it. The current version creates header rows that display API Names and you've changed that to extract the Labels instead. It seems reasonable that the people consuming reports are more interested in labels. Does that capture this change?

**Comment by jmdohn** [comment]
Yes, that's exactly right.

**Comment by jmdohn** [comment]
This may be better to pull out the specific class to reduce bloat in this class and include in the following:
https://github.com/alexed1/LightningFlowComponents/blob/master/flow_process_components/FlowBaseComponents/force-app/main/default/classes/fbc_FieldDescriptor.cls
https://github.com/alexed1/LightningFlowComponents/blob/master/flow_process_components/FlowBaseComponents/force-app/main/default/classes/fbc_GetFieldInformation.cls

I could abstract it to get relationship information much like what @danifin suggests. What do you think @alexed1?

**Comment by alexed1** [comment]
@jmdohn  Hi Jeremiah. I'm interested but not fully clear on what you're proposing in your comment from December 24. Which functionality do you suggest get pulled out of which class and where do you see it going? Very open to this kind of refactoring though.

**Comment by jmdohn** [comment]
Creating a new PR when changes are made.

**Pull request closed without merging**
