### PR TITLE
new lookup component

### PR DESCRIPTION
**Pull request by AndyHaas**
New LWC version of the Lookup component with some additional enhancements. 

Documentation:
https://docs.google.com/document/d/1-yW-7RBIMxDikP4eu3C-zE4zJ97mMSLGHkB1-sTYcuE/edit?usp=sharing

#1137 
#1242 
#1225 
#1132 

Old PR #1293

### CODE REVIEW

**Comment by alexed1** [comment]
can you update the documentation? It still points to  dependencies with fsc_ prefixes

**Comment by AndyHaas** [comment]
> can you update the documentation? It still points to dependencies with fsc_ prefixes

I have updated the document @alexed1

**Comment by AndyHaas** [comment]
@alexed1 are we ready to go live with this one yet? Or was there something on my docket to do?

**Comment by alexed1** [comment]
I'll get to work on it

**Review by alexed1 — COMMENTED** [review]
I put a couple of comments in but I didn't realize that they didn't get made visible to you because I hadn't committed my review, so I'm doing that now.

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
ok, going to try and package!

**Comment by alexed1** [comment]
looks like the test class is still calling 'fsc_lookupController' but it should be calling 'mc_lookupController' now, right?

**Pull request merged**
