### PR TITLE
ConvertCSVToRecords - Switch to UTF-8 encoding

### LINKED ISSUE #1052: ConvertCSVTo Records - Some special characters are not supported
Convert to CSV works great but does not handle some special characters, which makes it unusable for other languages than English (Spanish, French and German in my case)
### Steps to reproduce

1. Create a line on a CSV including the following characters for French:
2. â: ALT + 131 or 0226
à: ALT + 133 or 0224
ä: ALT + 132 or 0228
ç: ALT + 135 or 0231
é: ALT + 130 or 0233
è: ALT + 138 or 0233
ê: ALT + 136 or 0234
ë: ALT + 137 or 0235
î: ALT + 140 or 0238
ï: ALT + 139 or 0239
ô: ALT + 147 or 0244
ù: ALT + 151 or 0249
û: ALT + 150 or 0251
ü: ALT + 129 or 0252
œ: ALT + 0157

And this ones for Spanish : 
áéíóúüñ

And this ones for German : 
ß

+ the same exists in capital letters

2. Upload the CSV using the ConvertCSVto Records component

### Expected behaviour
The records created in Salesforce have the same charactersin Salesforce and in the CSV File

### Actual behaviour
The records in Salesforce are converted in some way. Here are a few example : 
ç becomes Ã§
è becomes Ã¨
é becomes Ã©
ñ becomes Ã±

### Workaround : 
I used a flow to substitute characters based on their outcomes. But it does not always work since some characters have the exact same output. So I cannot substitute them back to their original form.

@surajp

### PR DESCRIPTION
**Pull request by surajp**
To add support for accented characters and such that are not supported
by ISO-8859-1 encoding. Fixes #1052

### CODE REVIEW

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
Thanks for the great, simple fix!

**Comment by CodeKoz** [comment]
Thank you guys :) Great component.

**Comment by alexed1** [comment]
Here's 1.5 : https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G000003rUuXQAU
can you verify that it works as you expect?

**Comment by CodeKoz** [comment]
Hey!

I had the opportunity to test, and it seems to work well ! Great fix :-)

I had the secret hope that it would also enable using tsv in the process,
but I still cannot use it ( I made a ticket here :
https://github.com/alexed1/LightningFlowComponents/issues/932 )

Have a great day,

Le mar. 5 avr. 2022 à 16:38, Alex Edelstein ***@***.***> a
écrit :

**Pull request merged**
