### PR TITLE
Increased Functionality

### PR DESCRIPTION
**Pull request by rygramer**
Hey @jdayment - I added some functionality to your component. This is my first venture into LWC & the GitHub commit/pull/merge process, so feedback is welcome.
1. customize 'Uploaded Files:' label
2. required functionality with custom message
3. automatic icon selection based on file type
4. delete uploaded files in ui
5. return contentversionids and file names

### CODE REVIEW

**Comment by jdayment** [comment]
Awesome! Let me put this in my dev org and I will check it out!

**Comment by jdayment** [comment]
Great additions @rygramer! @alexed1 I tested on my end. I can do a post or @rygramer if you are up to it discussing the features or if you want to send me something around everything you added I can write it up. (you will get full credit!)

**Comment by rygramer** [comment]
Nice! @jdayment I can do a little write up over the weekend. I'll send it to you for review.

**Review by alexed1 — APPROVED** [review]
Sweet!

**Comment by alexed1** [comment]
New package version 1.2: https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G000003rUaCQAU

Definitely go ahead and create a new post. I just wrote up some general guidelines for what and how to write: https://unofficialsf.com/pauple_helpie/how-to-report-an-update/

**Comment by rygramer** [comment]
That's helpful @alexed1 - I will review

**Pull request merged**
