### PR TITLE
Added in-line edit feature.

### PR DESCRIPTION
**Pull request by spider-bkv**
To get it work you should:
1. Update property KeyField with existing unique column in your dataset
2. Set property "ColumnXX_editable" to True for columns you want in-line edit in.
3. Make sure that you set variable for "collection" property of your Object Type in "Store Output Values to Select Variables" section.

### CODE REVIEW

**Comment by alexed1** [comment]
Yowsa! This sounds like a great enhancement. Eric, when you get a chance can you give it a test drive?

**Comment by ericrsmith35** [comment]
I was planning on it.  I'll let you know.

Eric

**Comment by ericrsmith35** [comment]
This looks good.  Validation rules will apply errors if any changes trigger them.  Fields that are Lookups and Picklists can be edited, but as Text only without any validation checking.

The suggested code disables the Cancel/Save buttons and handles the updates when going to the next screen.  The creator of the Flow using the component will need to make sure they include an Update Records node after the screen to save the changes.

I say go ahead and pull in the changes and I'll look into enhancing it afterwards to include the Cancel/Save and provide instructions on looping back to the screen in case additional changes are desired.  The ideal way to handle this in the future will be to have an Apex controller handle the updating while the user is still Editing/Viewing the table.  Looking forward to generic SObject support ;-)

**Comment by spider-bkv** [comment]
Hey gents, nice to meet you and I'm glad my changes are useful!

@ericrsmith35 , Thank you so much for the test drive and deep review! You're completely right, I haven't planned to use the inline edit for immediate updating Records, only to show and to help the end-user with the data will be inserted/updated (it's used in a wizard right now).

Couple quick question, I'm new to Salesforce and haven't known about all limitations:
1. Which one holds us from having SObject typed attribute for any object? (instead of having those 8x2 attributes for in and out collections).
2. Is there any restriction on using some kind of dynamic set of attributes to prevent displaying all column related attributes in a long line? Or it might be a common way to set the flow setting with modal popup?
3. Is there a way to show a footer row with SUM/COUNT/AVG values in datatable?

We're going to use the flow extremely often, almost everywhere in our processes. So... I'm sure there will be much more improvements done! :)

Btw, I believe you know that they have similar component in SF: [Single-Select Table](https://help.salesforce.com/articleView?id=flow_ref_elements_screencmp_singleselect_table.htm&type=5) and [Multi-Select Table](https://help.salesforce.com/articleView?id=flow_ref_elements_screencmp_multiselect_table.htm&type=5).
But unfortunately, they hide it and it's available for Orgs with Financial Service Cloud license only :(
I contacted the support and they recommended to create an Idea: https://success.salesforce.com/ideaView?id=0873A000000PcssQAC
Honestly, I don't believe it will take effect soon, but at least it's a try :( 

Thank you!
Have a nice day all!

**Comment by alexed1** [comment]
> 1. Which one holds us from having SObject typed attribute for any object? (instead of having those 8x2 attributes for in and out collections).

Just a technical limitation of Flow that has held back action and component development for years. You're arriving at just the right time though. Next week, the first Spring '20 orgs start to go out, with support for generic SObject and SObject[] variables in Apex Classes. This support will then go into Flow Screen Components in Summer '20.

You can pass in anything dynamic you want as long as its concrete. Any limitations you find will probably be in the interface that the base Datatable component exposes. That's not open source itself, so we're limited to what our colleagues on the base component team publish.

**Comment by alexed1** [comment]
Approving the pull. Spider, I'd like to ask you to write a small blog post for unofficialsf that introduces your feature. send your email to aedelstein@salesforce.com (or post it here) and I'll give you access. Nothing fancy needed, and I'm happy to edit it.

**Comment by alexed1** [comment]
@ericrsmith35 , you need to Approve via your pull request for things to go properly.

**Comment by ericrsmith35** [comment]
2. The only restriction in setting the attributes is how you want to parse them in the component.  When generic SObjects are available this component will be redone to act on a single onject.

3. The component is only designed to show records in an object.  You would have to handle a total row as a separate component or a "custom" record in the object.

**Comment by ericrsmith35** [comment]
Alex,

I have opened a Pull request to add the Cancel & Save button functionality
to the table when editing.  I also updated the datatable parameter to use
the keyfield attribute being passed in.

When you approve the Pull Request, I will post additional documentation
updates to unofficialsf.com.

Eric

**Comment by spider-bkv** [comment]
> I also updated the datatable parameter to use the keyfield attribute being passed in.

@ericrsmith35 Thank you so much! My fault, missed it when was committing the changes :(

**Comment by ericrsmith35** [comment]
I have created a Blog post for inline editing (https://ericsplayground.wordpress.com/2019/11/30/enhance-your-flows-with-data-tables-part-4/) and I have updated the documentation on unofficialsf.com.  The last remaining step is to replace the v2.6 package link with the latest version of the source code.

**Pull request merged**
