### PR TITLE
Adding textAreaPlus

### PR DESCRIPTION
**Pull request by jdayment**
Worked with Nathan Shulman from SF on this one for another user looking to do this in flow from a post in OhanaSlack basically a way to display character count and validation on a plain text input field. I'll work with Nathan on a post. We have some ideas for more things to do on it.

### CODE REVIEW

**Review by alexed1 — APPROVED** [review]
looks like a great addition!

**Comment by alexed1** [comment]
I assume you'd like a package of it now?

**Comment by jdayment** [comment]
Yes I will get a post written up this weekend.

**Comment by alexed1** [comment]
Here's 1.0.0.0 https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G000003rUsWQAU

**Pull request merged**
