### PR TITLE
Responsive visual text boxes for Quickchoice

### PR DESCRIPTION
**Pull request by clifford-fra**
Quickchoice visual text boxes are now responsive in single column view. The height of the text boxes adapts to the content inside and the width changes with the window/view port size. Tested in single and dual columns view and with and without icons.

**Old:**
grafik

**New:**
grafik

### CODE REVIEW

**Comment by alexed1** [comment]
Niiicee! @ericrsmith35 wAnt to do the code review as the creator of the visual picker?

**Comment by ericrsmith35** [comment]
Sure - I'll do some testing.

**Comment by ericrsmith35** [comment]
To keep the behavior the same for existing Flows using this component, I added an option to the CPE to "Make Card Size Responsive".  The default is False and the CPE will only display the selection when Visual Cards and Single Column are selected.

**Comment by ericrsmith35** [comment]
The CPE Label update is to clarify what Labels and Values are when using Visual Cards

**Review by alexed1 — APPROVED** [review]
Eric can you update the main doc post as necessary...i'll package

**Comment by alexed1** [comment]
@clifford-fra thanks again for improving this component. I see in your repo you have a couple of other flow extensions. Do you think any of them are ready to publish? we're always interested....

**Comment by clifford-fra** [comment]
@alexed1 My Google Recaptcha Component on unofficialsf.com is already pretty popular. I think my NavigateByKey component would also be a nice addition. Currently, the component navigates to the next Screen by pressing Enter. Let me overhaul the component a bit, and I will contact you or Eric as soon as I'm finished.

**Comment by ericrsmith35** [comment]
I have updated the component page and the screen component table.
https://unofficialsf.com/quick-choice-improved-picklists-and-radio-buttons-for-flow/

**Pull request merged**
