### PR TITLE
SendHTMLEmail Version 1.33.01 Updates for Issues #308,#316

### PR DESCRIPTION
**Pull request by jdpond**
1.	Add STRONG Documentation/Release notification that saveAsActivity is now default to false. Emails previously saved as activities without explicitly using saveAsActivity = true will stop
2.	Default saveAsActivity now set to false
3.	Activities created with Templates now have subject and recipients in Task Comments
4.	Added Activity Date (Today) to Task Activity
5.	Update Documentation with new example flow information
6.	Changed the test to use Account versus Case for full test
7.	Added @Test t013_CoverageAttemptForOrgWideEmailAddress
8. 	Updated package name that does not contain the examples to "sendHTMLEmail(Without Examples)"
9.	Create and maintain a managed package(2, one for with test, one without) for this component

SendHTMLEmailTest test results:
78% with TEST_WITH_CREATED_RECORDS = false (released value)
92% with TEST_WITH_CREATED_RECORDS = true (test prior to released value)

### CODE REVIEW

**Comment by jdpond** [comment]
I will create packages, make updates needed to https://unofficialsf.com/send-rich-email-with-the-new-sendhtmlemail-action/ and do a new post for the releases when merged.

**Comment by jdpond** [comment]
@alexed1 FYI

1. Updated [Send Rich Email)(Send HTML Email Action)](https://unofficialsf.com/send-rich-email-with-the-new-sendhtmlemail-action/)
2. Created draft post for notification (publish if ok)[Send Rich Email (Send HTML Email Action) Ver 1.33.1 — Draft](https://unofficialsf.com/wp-admin/post.php?post=17879&action=edit)
3. Was thinking of publishing this for helping users to do package upgrades [Tips & Tricks – Update/Upgrade an Unmanaged Package — Draft](https://unofficialsf.com/wp-admin/post.php?post=17965&action=edit).  If OK, will do and add a line about "if your having problems" in the Installation section.
4. Working on the CPE stuff now.  #320 will wait until meaningful parameter handling - too much there already.

**Comment by ericrsmith35** [comment]
I like your notes on reinstalling unmanaged packages.  If Flow parameters
change or some are removed, the user may have to even delete those flow
versions or remove the component from the flow.

Another option to install a new version of an unmanaged package is to
install it in a Sandbox that does not already have the component in it and
then use a Change Set to move the new version to other Sandboxes or to
Production.

Eric Smith

**Comment by alexed1** [comment]
That's really interesting. I'm not familiar with that approach, Eric. If
the production system that you're moving the package to via change set has
a piece of metadata with the same name as the piece that's in the package,
but they don't contain identical content, what happens?

Alex Edelstein
Sr. Dir. Product Management - Automation and Decisioning
Salesforce

<https://smart.salesforce.com/sig/aedelstein//us_mb/default/link.html>

**Comment by alexed1** [comment]
Jack, looks great. 
Add a link to your Upgrade post to this wiki page to make it more easy to find: https://unofficialsf.com/the-salesforce-automation-and-decisioning-wiki/flow-testing-and-deployment/
Go ahead and publish all of this.

People will start getting preview releases in 2 days. I think what I'm going to do is just add the CPE to the main Send Email project this weekend. I'll create a version 2.0 that requires Summer '20 but we'll leave up the 1.33.01 version until Spring '20 is no longer available. 

If we decide we need to do a new version of the Spring '20 code, all we have to do is edit out the one 'configurationEditor' property in the invocablemethod annotation and it will generate a package without the CPE.

**Comment by ericrsmith35** [comment]
Alex,

I've had it work before.  I'll pay more attention next time I try it and
let you know what I see.

Eric

**Comment by jdpond** [comment]
I released the above documentation stuff this AM as above.
Re: "If  the production system that you're moving the package to via change set has
 a piece of metadata with the same name as the piece that's in the package,
 but they don't contain identical content, what happens?"
I have too @ericrsmith35 - as a matter of fact, that was the way I was doing it when I realized if we released 1.33.1 and that was the only way to do the upgrade, we were in for a whole string of comments/issues asking for support.  I had so much trouble upgrading my 0.1 orgs to 1.33 that I realized I was incapable of explaining the "how" to someone else.

I stood back a few days and explored the "remove" alternative in [TIPS & TRICKS – UPDATE/UPGRADE AN UNMANAGED PACKAGE](https://unofficialsf.com/tips-tricks-update-upgrade-an-unmanaged-package/) and found it worked in every case I tried and was much easier to implement.  HOWEVER, I do believe that in situations where there are issues around changed parameters and deprecated components the changeset alternative would be required.   We have tried VERY hard to make sendHTMLEmail backward compatible so I'm hoping changeset approach would not be necessary.

**Comment by jdpond** [comment]
Alex, just as an FYI, I'm going to go back and enable CPE too - mostly as an exercise in how to do it. 
Will merge with yours when released.  Was thinking that 1.33.2 of sendHTMLEmail will be after Summer '20.  Everything after 1.33.1 should have CPE enabled.
I'm waiting for Pilot approval from case 26273816 for pilot enablement, https://partners.salesforce.com/partnerCaseDetails?id=5000M00000sWh8n 

> Jack, looks great.
> Add a link to your Upgrade post to this wiki page to make it more easy to find: https://unofficialsf.com/the-salesforce-automation-and-decisioning-wiki/flow-testing-and-deployment/
> Go ahead and publish all of this.
> 
> People will start getting preview releases in 2 days. I think what I'm going to do is just add the CPE to the main Send Email project this weekend. I'll create a version 2.0 that requires Summer '20 but we'll leave up the 1.33.01 version until Spring '20 is no longer available.
> 
> If we decide we need to do a new version of the Spring '20 code, all we have to do is edit out the one 'configurationEditor' property in the invocablemethod annotation and it will generate a package without the CPE.

**Comment by alexed1** [comment]
That sounds great. I will leave the merge of the CPE into Send Rich Email
in your hands.

Note that in Summer '20 all the CPE is in Beta and you don't need any
enablement. Just grab a Preview Release org. (see the link at the top of
https://unofficialsf.com/summer-20-flow-preview/)



Alex Edelstein
Sr. Dir. Product Management - Automation and Decisioning
Salesforce

<https://smart.salesforce.com/sig/aedelstein//us_mb/default/link.html>

**Pull request merged**
