### PR TITLE
Winter 23 Fix - fire attributes

### PR DESCRIPTION
**Pull request by ericrsmith35**
The fire attributes stopped being sent back to the flow in Winter 23.  This fixes that issue.

@alexed1 Please repackage and send me a confirmation so I can update the unofficialsf pages.

### CODE REVIEW

**Comment by alexed1** [comment]
will do. Once this bug is fixed for Winter 23, will we have to make another change here?

**Comment by alexed1** [comment]
on my initial search, it looks like this was never packaged. I also can't locate a blog post about it. VS Code says you touched it in 2018 and I touched it '4 years ago'. Did you spot a post where we talk about it?

**Comment by ericrsmith35** [comment]
I have created a new package and updated the documentation.  I'll send another PR with a minor change to the test class

**Comment by ericrsmith35** [comment]
This will not require any changes after a W23 "bug fix" is completed.

**Pull request merged**
