### PR TITLE
Fixed the Unit Test to support Platform Encryption

### PR DESCRIPTION
**Pull request by hasnainkurawadwala**
Updated ConvertRecordsToCSVQueueableTest unit test to support Platform Encryption - fixed the assertion and Aggregate Results errors.

### CODE REVIEW

**Comment by hasnainkurawadwala** [comment]
Hey, @alexed1 just wanted to check if you are able to review and merge this PR. We have our production go live in a couple of weeks and this component is breaking our deployment due to platform encryption.

**Comment by hasnainkurawadwala** [comment]
@alexed1 - Updated the test class to resolve the sorting issue. The AggregateResults returned the contacts sorted by LeadSource in some orgs and unsorted in others. Added an Order By clause to handle the issue. 

@Hope-19 - can you please test the latest change in your org and confirm. Thank you!

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
I merged this in and tried to build a new base pack but got this error:  Apex Test Failure: Class.usf3.ConvertRecordsToCSVQueueableTest.testGenerateCSVContentAggregateResult: line 78, column 1 System.AssertException: Assertion Failed: Expected: Social, Actual: Web

**Comment by hasnainkurawadwala** [comment]
Hi @alexed1 - the asserts failed because the AggregateResult returns result in a different order in different orgs/sandboxes. I fixed the test class and updated the asserts and tested in multiple sandboxes. Here is my new PR - https://github.com/alexed1/LightningFlowComponents/pull/1143

Thanks,
Hasnain

**Pull request merged**
