### PR TITLE
Quick Choice InstantNavigation Mode

### PR DESCRIPTION
**Pull request by ChewinChaz**
As requested, I have added the navigation feature code into the fbc version of Quick Choice.  As soon as I receive the login info I will create a blog post outlining the new functionality for your review.

Email for login: sirchaseman@gmail.com

### CODE REVIEW

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
update: I have this into the latest basepack, and the post is ready to go. just delayed on an unrelated packaging issue with the basepack

**Comment by ChewinChaz** [comment]
Thanks for the update!

On a completely unrelated note, I have been playing around with the lightninginputFSC component and realized that when a Number input is focused on the mobile app, it brings up a numeric keyboard.  The standard number flow component currently still renders a full alphanumeric keyboard which can be incredibly aggravating for users such as mine who are entering numerical data several times a day while in the field.  Anyways, I'm sure there are many admins who would love to know about that ability so I thought I'd suggest adding it to the documentation if you think it'd be worthwhile.

**Comment by ChewinChaz** [comment]
Hi Alex.  I saw that the new flowbasecomponents pack contains the updated QuickChoice with Instant Navigation Mode.  I haven't seen the blog post up yet so wanted to drop you a reminder in case it had slipped your mind.  Let me know if there's anything else you need from me!

**Comment by alexed1** [comment]
As you can see from https://unofficialsf.com/introducing-flow-basepacks/ , we've retired flowBaseComponents and replaced it with two packages including flowScreenComponentsBasePack. Verify that your code is present in the QuickChoice that's located at https://github.com/alexed1/LightningFlowComponents/tree/master/flow_screen_components/FlowScreenComponentsBasePack. Change the blog post to point to this new basePack package and let's publish it.

**Comment by alexed1** [comment]
re: number input, feel free to make an edit to the documentation and create a PR. bigger challenge is probably making people aware of lightningInputFSC in the first place...

**Comment by ChewinChaz** [comment]
I've confirmed the flow basepack has the new InstantNav code in it and I have published the blog post.

Concerning the lightning input, a blog post detailing why it is superior to the standard inputs might be the best way to go.  Personally, I've read through each of the action and screen flow components on USF and installed the majority of them, but only installed the lightning input component recently as I didn't really see a benefit of using them over the standard flow components, which don't carry the same risk of breaking on new releases.  Updating the documentation and a blog post listing the advantages of using the USF version (such as the numeric mobile keyboard) might help it get more traction.

**Comment by alexed1** [comment]
would you be interested in writing the post?

Alex Edelstein
VP Product Management - Automation, Orchestration and Decisioning
Salesforce

<https://smart.salesforce.com/sig/aedelstein//us_mb/default/link.html>

**Pull request merged**
