### PR TITLE
Add Base64ToFileConverter Action

### PR DESCRIPTION
**Pull request by jdayment**
Adds Base64 to File Converter 

Action has an input to accept a string value of your Base64 then saves to SF as ContentVersion.

### CODE REVIEW

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
nice. I'll create a package for this, Josh. Do you have a simple article we can post?

**Comment by jdayment** [comment]
Let me get one together

**Comment by jdayment** [comment]
@alexed1 I have a post ready to go when you get the chance to package.

**Comment by ericrsmith35** [comment]
I'll package this for you @jdayment

**Comment by ericrsmith35** [comment]
Package Installation URL: https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G000004fzAlQAI

Let me know when you have the article and I'll post it to USF and add it to the Actions Table of Contents

**Comment by jdayment** [comment]
Thank you!! I was able to publish the post this morning

**Pull request merged**
