### PR TITLE
Add DedupeSObjectCollectionInvocable

### PR DESCRIPTION
**Pull request by agentgill**
Super simple dedupe of a generic sobject collection. There are a couple of ways to handle this directly in flow, but involves looping and/and multiple assignment elements. This is just sobject collection in / out, job done.

### CODE REVIEW

**Comment by adwhite75** [comment]
@alexed1  I am happy to upload the source for that in here and we can make adjustments as needed - just let me know!

**Comment by agentgill** [comment]
Sorry got slammed after issuing this one. Would be good to see / have @adwhite75 upload his code if his code is very close. It feels like the pattern to handle dedupe based on the field would be different from the approach I used, not sure. The use case I was addressing was performing multiple get records across the same object type and feeding the collection into a data table - I was looking for a simple way to dedupe list collection.

**Comment by alexed1** [comment]
Great! go ahead and create a PR for the original dedupe, Adam, and let's compare the two

**Comment by adwhite75** [comment]
@agentgill  sorry I am behind on getting the code in here! Havent forgotten

**Comment by alexed1** [comment]
no problem. looking forward to it.

**Comment by adwhite75** [comment]
@agentgill  here is the code: https://github.com/adwhite75/LightningFlowComponents/tree/RecalculateFormulas/flow_action_components/DedupeRecordCollection/force-app/main/default/classes

I didnt get around to making a test class for it yet

**Comment by alexed1** [comment]
@agentgill let me know if you'd like to take a look at this. The question is mainly: can this be a single action instead of 2? It's in our interest to avoid fragmentation. However, if you don't have time, totally understand, and really appreciate your contribution.

**Comment by alexed1** [comment]
I'm going to close this for now, but we can reopen it anytime

**Pull request closed without merging**
