### PR TITLE
sendBetterEmail 2.0.5 Release: setTreatTargetObjectAsRecipient Fix: #586,ReplyEmail with SendBetterEmail #595, #598,#602

### PR DESCRIPTION
**Pull request by jdpond**
This release incorporates the setTreatTargetObjectAsRecipient needed by World WIde United Way and the setInReplyTo parameter suggested by @munawirrahman.

It includes several cleanups and bug fixes, but the restructuring of the mapping was reverted until a later release.

This fix is 100% forward compatible, so existing installations should require no updates.

Dependent current releases of FlowActionsBasePack(2.1.0-0) and FlowScreenComponentsBasePack(2.1.6-0) (brilliant work on fsc_flow-checkbox by @ericrsmith35)

Additional example flow added for testing both.
Fix: #586 New Function + FSC_Checkbox  -  Fails when contact has no email even if toAddresses are specified
Fix: #595 Support ReplyEmail
Fix: #598 (full credit to @peanutman21) File Name on Attachment is Incorrect
Fix: #602 SendBetterEmailUtil - Template Description empty causes error

Beta Package available here: 
[sendBetterEmail Version 2.0.5.beta 1](https://login.salesforce.com/packaging/installPackage.apexp?p0=04t4U0000011VU5QAM)

Remember - if you use the beta package you will have to uninstall it to install the release package - saving work from beta is a bear.

### CODE REVIEW

**Comment by jdpond** [comment]
Existing functionality not modified, only enhancements and bug fixes.

Will update documentation for these two features when pull request reviewed.

**Comment by peanutman21** [comment]
@jdpond - I installed Version 2.0.5 in a Sandbox to try things out. When I tried executing the Flow, I got the following error: 
Error Occurred: An Apex error occurred: System.SObjectException: SObject row was retrieved via SOQL without querying the requested field: ContentVersion.Title
Attached is the Debug Log.
Please let me know what you think. Thanks!
[apex-07L2900000OdxtTEAR.log](https://github.com/alexed1/LightningFlowComponents/files/5993609/apex-07L2900000OdxtTEAR.log)

**Comment by jdpond** [comment]
Thank you @peanutman21 Forgot a file in the package.  Check it again? (new package created)

**Comment by peanutman21** [comment]
@jdpond  - We are getting closer! The Flow ran all the way through and the name of the file is now the Title which is good. However, it seems that the file is missing the extension at the end (.PDF, .DOCX, .XLS, etc.). So when the attachment comes over on the email, it looks the attached. 
Fill Name Missing the Extension
Please let me know what you think. Thanks!

**Comment by jdpond** [comment]
@peanutman1 check my profile and contact me directly - let's debug this on a scratch org together

**Comment by jdpond** [comment]
@peanutman21 devoted several hours today to get attachments working properly - and we accidently discovered they never had been working correctly (all the way back to sendRichEmail).

We think the PR is ready to go

**Comment by alexed1** [comment]
Hey, @peanutman21, welcome to the Secret Order of Flow Extenders! Thanks for your help. Standby....

**Comment by alexed1** [comment]
ok, here's package version 2.1.0.0 of SendBetterEmail. Test it out a bit and I'll put it up on the site:
https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G000004Pud8QAC

**Comment by peanutman21** [comment]
@alexed1  - It was great working with @jdpond on this. Thanks to the both of you for all you do for UnofficialSF!

**Pull request merged**
