### PR TITLE
lookupUpdate2

### PR DESCRIPTION
**Pull request by professorFlow**
I am trying this again.

### CODE REVIEW

**Comment by alexed1** [comment]
excellent! @ericrsmith35, can you take a look?

**Comment by ericrsmith35** [comment]
I was able to update a sandbox by pulling in the current source code, implementing the changes and get it to work.  Did you end up removing the magnifying glass symbol from the input box?

**Comment by professorFlow** [comment]
image

It is showing up for me?

**Comment by ericrsmith35** [comment]
Al  set for me too.  I was looking on the left side where the original
component had it ;-)

**Comment by professorFlow** [comment]
Gotcha - I can change it but I used what is in LDS (https://www.lightningdesignsystem.com/components/lookups/)

**Comment by ericrsmith35** [comment]
Stick with what is current for design.  The original look is very old.

**Comment by alexed1** [comment]
Eric, since you have been requested for a code review here, you need to "complete" it before this pull request can be merged.

**Comment by ericrsmith35** [comment]
Ok to go

**Pull request merged**
