### PR TITLE
Common and uncommon update

### PR DESCRIPTION
**Pull request by jmdohn**
Updates schema describes to be cached in a map:
sobjectTypeMap of type Map<String, Map<String, SObjectField>>

This results in less describes and decreased CPU time usage.

### CODE REVIEW

**Comment by adwhite75** [comment]
Awesome thanks Jeremiah!

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
cool....nag me if I forget to repackage

**Comment by alexed1** [comment]
getting this test failure when I package:
ERROR running force:package:version:create:  Apex Test Failure: Class.FindCommonAndUniqueRecordsTest.testEmptyCollection: line 81, column 1 System.ListException: List index out of bounds: 0

**Comment by jmdohn** [comment]
@alexed1, I was missing some logic that was previously there for empty list handling.  After adding this back, all seems to be well. I created [a new PR ](https://github.com/alexed1/LightningFlowComponents/pull/826)for this.

**Pull request merged**
