### PR TITLE
Inline picklist editing for Datatable 3.11

### PR DESCRIPTION
**Pull request by gudavies**
Added support for inline editing of picklist field from Flow Data Table.
Maintains editable flag, and yellow highlight on editing.
Switches the styling of overall table to allow combo box overflow in case of larger lists, when a set max height is not set on the table.

Considerations:
Pulls values from existing apex class which does not filter to record type values, should be improved in future to use new LWC function to get RT filtered picklist values.
Does not yet support dependent picklist filtering.

### CODE REVIEW

**Comment by ericrsmith35** [comment]
Thanks Guillaume, I'll work these changes into my upoming release.

**Comment by alexed1** [comment]
Sweet!

**Comment by ZespriKiwi** [comment]
the custom datatable was a fun challenge, and you can easily extend it to allow other column types in the future.
However, one thing to note is that the static resource was required to load the css in order to bypass the shadow dom. this was required to address the picklist overflow issue and the yellow highlight.

**Comment by ZespriKiwi** [comment]
the custom datatable was a fun challenge, and you can easily extend it to allow other column types in the future.
However, one thing to note is that the static resource was required to load the css in order to bypass the shadow dom. this was required to address the picklist overflow issue and the yellow highlight.

**Comment by ericrsmith35** [comment]
@JerrycsPoon I'm off to a reasonable start, but I have run into a few issues.  

1. Changes to the Picklist fields don't save the new values nor do they change the highlight color.  
2. When adjusting a column width by dragging one of the column separators, I get this error: 
_This page has an error. You might just need to refresh it. [Cannot read property 'offsetWidth' of null] Failing descriptor: {markup://lightning:datatable}_
3. The dropdown symbol in the picklist cells appear on top of any display from selecting the column header dropdown
4. Is the original richDatatable folder and its contents still required?

You can find the current version of the source code that I'm testing here: https://github.com/alexed1/LightningFlowComponents/tree/dt311/flow_screen_components/datatable/force-app/main/default

**Comment by JerrycsPoon** [comment]
hi @ericrsmith35,
I'll have a look tonight. 

1. Changes to the Picklist fields don't save the new values nor do they change the highlight color.
Not too sure about this one. It worked when there is the 'next button'. Is your scenario without the 'next' button? For the highlight - did you include static resource as part of the deployment? 

2. When adjusting a column width by dragging one of the column separators, I get this error: This page has an error. You might just need to refresh it. [Cannot read property 'offsetWidth' of null] Failing descriptor: {markup://lightning:datatable}
I vaguely remember this one - wasn't sure if it's a result of my change. I think i added a null checker somewhere. I'll have look tonight

4. The dropdown symbol in the picklist cells appear on top of any display from selecting the column header dropdown
Is the original richDatatable folder and its contents still required?
Good catch. Interestingly this behaviour exists without css changes i've made. I may need to add something in the css

**Comment by JerrycsPoon** [comment]
hi @ericrsmith35 I've made some changes to the styling. You can view the pull request here: 
https://github.com/alexed1/LightningFlowComponents/pull/685/files

This should address the highlight on change, and the dropdown icon overlapping the column actions.

I'll need to investigate the save issue. Could you please check if the 'next' button is enabled?
for 2., I am unable to reproduce this issue. This looks to be coming from SF component lightning:datatable which is weird.

**Comment by ericrsmith35** [comment]
@JerrycsPoon I've created a video showing the current issues i'm seeing with the recent changes.
https://drive.google.com/file/d/1UP3PZlrFvyalabuTQ5IanCvQSeSjjpgg/view?usp=sharing

**Comment by ericrsmith35** [comment]
@JerrycsPoon Here's the issue I'm seeing when changing column widths.  

https://user-images.githubusercontent.com/24724447/114423502-3c539b80-9b85-11eb-9bc7-5a7312bcb5df.mp4

**Comment by JerrycsPoon** [comment]
hi @ericrsmith35  thank you for the videos, they are very useful.
The richDatatable is not required. I moved everything from richDatatable to customLightningDatatable. richDatatable only contained the rich text, and so I moved everything to a more generic component


Regarding the overall build...
I haven't tested it using 'Run' directly. I believe the selectors might differ a bit when 'run' is clicked. I've been testing the build by adding the component on a flexipage.

I'll find some time over the next few days to address these issues.

**Comment by JerrycsPoon** [comment]
hi @ericrsmith35 I found some time and addressed most of issues. I've recorded a video to go through the changes and what is left:

1. highlight persisting after save
2. offsetwidth null issue: https://1drv.ms/u/s!AuLD0wB2J44DiFTuL4Qwik2VQvxi?e=fpotKK

**Comment by ericrsmith35** [comment]
This is great, thank you.  I'm curious, however, why one of the highlights
covers the entire cell and the other is just highlighted inside of the
selection box.

[image: image.png]

Eric

**Comment by ericrsmith35** [comment]
Nevermind on that previous question, I think the full cell gets highlighted when it is the currently selected cell.

I'm still not getting the edits to work.  I've attached another video.  Please compare your codebase with what I currently have in the dt_picklist branch and see if I'm still missing something.

https://1drv.ms/v/s!Akbs_lceUmo-hrVZ89gx6Fh4D-ZAhA?e=u2FDNI

**Comment by JerrycsPoon** [comment]
hi @ericrsmith35 sorry I forgot to mention the pull request is https://github.com/alexed1/LightningFlowComponents/pull/693/files, which @alexed1 has correctly pointed out. The changes in this request are missing in dt_picklist.

Sorry I wasn't sure which branch you were working on, so I was merging into dt311 from previous comments. 

Let me know if it helps. If there are still issues maybe we can set up a call? thanks

**Comment by ericrsmith35** [comment]
Jerry,

I do have that code installed.  There must be some other differences in the
code that I'm not aware of.  I'd be glad to have another call if that would
help.

Eric

**Comment by JerrycsPoon** [comment]
hi @ericrsmith35 I did a comparison and saw a missing line. I've created a pull request.
https://github.com/alexed1/LightningFlowComponents/pull/696/files

I reproduced your error when I used the code from your branch, and could see it fixed when I added the extra line. 

I'll shoot you a personal email and we can reconvene some time this week/next week.

hope it works!

**Comment by ericrsmith35** [comment]
It is working now Jerry.  Thank You.  I'd love to chat sometime about the
formatting and about adding an option to edit a lookup field.

Eric

**Comment by alexed1** [comment]
@ericrsmith35 @JerrycsPoon what would you like to do with this pull request? It's still in draft state. is it ready to be merged?

**Comment by ericrsmith35** [comment]
No, it is not ready yet.

Eric

**Comment by ericrsmith35** [comment]
applied

**Pull request closed without merging**
