### PR TITLE
Encryption-failed---field-'LastName'-can-not-be-grouped-in-a-query-call

### PR DESCRIPTION
**Pull request by Hope-19**
Encryption-failed---field-'LastName'-can-not-be-grouped-in-a-query-call

### CODE REVIEW

**Comment by knomenot** [comment]
> @alexed1 Hi Alex, this change will solve the "FlowActionsBasePack 2.36 fails install with Contact.LastName encrypted #1092" issue. At this moment, we are not anble to encrypte Account/Contact name which is very crucial in our org and should be done asap. Could you please check it?

Would it possible to know when this will added to next managed package release this commit is critical to our project that has Salesforce Shield.

**Comment by hasnainkurawadwala** [comment]
Hey, @alexed1 is there a planned date when this change will be added to the managed package? We are running into this issue with the current version and it is critical to our go-live this month.

**Comment by alexed1** [comment]
Hi @Hope-19. Thanks so much for this improvement. I went to package this change but got a test failure: 
Apex Test Failure: Class.usf3.ConvertRecordsToCSVQueueable.generateAggregateResultCSV: line 189, column 1
Class.usf3.ConvertRecordsToCSVQueueable.generateCSVContent: line 164, column 1
Class.usf3.ConvertRecordsToCSVQueueableTest.testGenerateCSVContentAggregateResult: line 72, column 1 System.SObjectException: Invalid field name for AggregateResult

Were you able to run the tests in ConvertRecordsToCSVQueueableTest ? Is this something that you can take a look at?

**Comment by Hope-19** [comment]
Hey @hasnainkurawadwala 
it's very strange. I get issue using your test class in my sandbox. can you please check the last version I put here and see if it's working for you? 
https://github.com/Hope-19/LightningFlowComponents/blob/master/flow_action_components/FlowActionsBasePack/force-app/main/default/classes/ConvertRecordsToCSVQueueableTest.cls

**Pull request merged**
