### PR TITLE
File Upload

### PR DESCRIPTION
**Pull request by jdayment**
Here's what I have so far it functions I just can't get my collection of Id's to output.

### CODE REVIEW

**Comment by alexed1** [comment]
Thanks!

This PR has some flowcarousel files in it....

**Comment by alexed1** [comment]
I recognize the problem you're running into. It's one of those nonintuitive javascript weirdnesses. At least these days there's a big of explanation here:https://lwc.dev/guide/javascript

image

You basically can not directly assign a value to a property that has @api in front of it.  You know how you sometimes see data structures like this to get around this:

@api foobar;

get _foobar() {
    return foobar
}

set _foobar() {
  return this.foobar;
}

**Comment by jdayment** [comment]
Cool I'll see what I can figure out unless Eric gets to it before I do. Now that I look at it those carousel files can probably be merged also I thought I put in a or for them and forgot. I added a property for the admin to set the slide style that wasn't in the initial pr

**Comment by jdayment** [comment]
This PR includes some minor changes to flowCarousel to allow admin control slide styling and also add fsc_FileUpload to the repository.

**Review by alexed1 — APPROVED** [review]

**Pull request merged**
