### PR TITLE
Flow Barcode Scanner Update along with some Flex Card Updates

### PR DESCRIPTION
**Pull request by jdayment**
Updates Barccode Scanner Component to support continuous scan capability. Also included styling updates for flow Flex Card. Gives admins more control over styling of the cards. I will update both posts with changes once they are merged.

### CODE REVIEW

**Comment by alexed1** [comment]
This is great, Josh. Can you provide a bit of documentation for this? A google doc would be fine.

**Comment by jdayment** [comment]
I planned on updating the original post I can also put into a Google doc if
you would like

**Comment by alexed1** [comment]
no need that's fine

**Review by alexed1 — APPROVED** [review]
Great improvements, Josh! Thanks for your patience.

**Comment by alexed1** [comment]
Here's version 1.1 of barcode scanner: https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G000004J7JjQAK

**Pull request merged**
