### PR TITLE
Set default

### PR DESCRIPTION
**Pull request by ryemcc**
Makes requested changes to pr #122. Implements feature for adding default value originally suggested by @chexxor; updates readme; removes unused code in helper.

### CODE REVIEW

**Comment by alexed1** [comment]
I accepted 122 because I thought this one would be additive to it....I'm seeing some conflicts reported here, so maybe your intent was to bypass 122 and just merge 125? sorry if I erred here....

At this point, I think the best thing to do is resolve the conflicts here and then merge this.

**Comment by alexed1** [comment]
Hi, Ryan. Just checking in on this. can it be closed because I accepted 122? If we should also accept this one, can you resolve the conflict? Sorry about the confusion.... really appreciate your contribution here

**Comment by alexed1** [comment]
Hi, Ryan. Just checking in on this. can it be closed because I accepted 122? If we should also accept this one, can you resolve the conflict? Sorry about the confusion.... really appreciate your contribution here

**Comment by ryemcc** [comment]
Hey @alexed1, I've resolved the conflicts.

**Pull request merged**
