### PR TITLE
Multirow and Box for flexCard

### PR DESCRIPTION
**Pull request by jdayment**
I added multi row support. Boxes around each card and updated the header to reference a custom field called src_URL__c that will optionally need to be created on any object where it is desired to show a custom icon in lieu of standard lightning icons.

### CODE REVIEW

**Comment by alexed1** [comment]
@jdayment note the conflicts above. Are you familiar with resolving merge conflicts?

**Comment by jdayment** [comment]
> @jdayment note the conflicts above. Are you familiar with resolving merge conflicts?

I am not doing a PR is about my entire knowledge with GitHub

**Comment by jdayment** [comment]
I figured it out I think let me know if I messed it up.

**Review by alexed1 — APPROVED** [review]
Good work. merging can be a little intimidating, but at the end of the day, it's just 'make these two text files the same'

**Pull request merged**
