### PR TITLE
Dt picklist

### PR DESCRIPTION
**Pull request by ericrsmith35**
Current source code for datatable v3.2.0

### CODE REVIEW

**Review by alexed1 — COMMENTED** [review]
renaming files for existing extensions makes me very nervous these days...we've just had so many issues with upgrading failing. What's the motivation for renaming these classes? Do we know that upgrading will work without problem?

**Comment by ericrsmith35** [comment]
The base component (datatable) was not renamed.  The only files renamed were ones referenced by datatable.  The reson for this is to reduce the conflicts users are starting to see when insalling multiple unlocked packages where different developers have chosen the same names for various pieces of their components.

**Comment by ericrsmith35** [comment]
There is another developer out there who has a datatable component geared towards use by developers and it can't be installed in the same org as mine because he also uses "datatable".

**Comment by ericrsmith35** [comment]
BTW, I have installed this update, as have others, and I've seen no issues with the renaming.

**Pull request merged**
