### PR TITLE
Bug fix for different date formats

### PR DESCRIPTION
**Pull request by surajp**
There was a bug in the routine for handling multiple date formats. This is the fix for that. Also contains additional tests for testing different date formats in the csv.

### CODE REVIEW

**Comment by surajp** [comment]
I originally had listed this as the fix for #937 , but this won't handle `MM-DD-YYYY` date format. That would require introduction of an additional date format input property, and I don't believe its worth complicating the action for that

**Comment by surajp** [comment]
> Thanks, Suraj. I think it's worth adding a way for spreadsheets that have columns that are in MM-dd-yyyy will work here without modification. Is that something you could do?

Ok, @alexed1 . I will add an additional parameter for user to specify the date format (either MM-dd-yyyy or dd-MM-yyyy). If left blank, the format will be assumed to be either yyyy-MM-dd or the user's local date format in the org.  I will let you know when it's ready to merge

**Comment by surajp** [comment]
@alexed1 any updates on when this might be merged?

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
I'll merge it now. Thanks for your patience and your fixes!

**Comment by alexed1** [comment]
Posted as version 1.4...test it out if you get a chance. Thanks for your contributions again, Suraj!

**Pull request merged**
