### PR TITLE
Initial Commit Barcode Scanner

### PR DESCRIPTION
**Pull request by jdayment**
My initial build on a simple QR code scanner which can be used in flow on mobile devices. You can use other barcode formats but you are limited by device and I am limited by my javascript knowledge still learning but have some unique use cases in our business for this. The documentation where I stole this from is below. I extended it to use in flows and return the value. 

https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.use_barcodescanner_intro

### CODE REVIEW

**Comment by alexed1** [comment]
Nice one! can you add some documentation? I like to have authors create their own blog posts on unofficialsf that serve as documentation, so if you want to provide me with your email address, I'll give you an author credential

**Comment by jdayment** [comment]
sure thing it's easier if you do josh.dayment@recruitmilitary.com

**Comment by alexed1** [comment]
Great. just added an author account. Go ahead and draft a post. then I'll merge this and build a package that we can add to your post.

**Comment by jdayment** [comment]
Awesome I'll get something drafted tonight or tomorrow morning

**Comment by jdayment** [comment]
Draft post is saved to the site.

**Comment by jdayment** [comment]
I also updated the js today to allow for the full spectrum of supported Barcode Types it was previously only for QR but now it will scan most common types.

**Review by alexed1 — APPROVED** [review]
Great addition, Josh!

**Comment by alexed1** [comment]
Here's a package. can you verify it works correctly? One anomaly was that sfdx didn't like the jsconfig.json file  in the lwc folder. I moved it to the root of the project and was able to build the package.

https://login.salesforce.com/packaging/installPackage.apexp?p0=04tf4000004PuTMAA0

**Comment by jdayment** [comment]
Everything works as expected. I was having some issues with github on my desktop I'm wondering if the job was corrupted during that fun exercise of uninstall reinstall remove from one drive and resync 😀

**Comment by alexed1** [comment]
ok, post is live!
alex

Alex Edelstein
VP Product Management - Automation, Orchestration and Decisioning
Salesforce

<https://smart.salesforce.com/sig/aedelstein//us_mb/default/link.html>

**Pull request merged**
