### PR TITLE
Text Area Plus Bug Fixes and Feature Enhancements and updates to FSC Action List and add FSC Modal Flow for Flow Flex Card

### PR DESCRIPTION
**Pull request by jdayment**
Text Area Plus

- Fixes issue where session storage was not being cleared on validation and previous when multiple components on one screen
- Adds Display Text option

FSC Action List and FSC Modal Flow

- Utilized Lightning Modal (part of Winter 23' release) to launch flow in modal now instead of old framework

### CODE REVIEW

**Review by alexed1 — APPROVED** [review]

**Comment by alexed1** [comment]
thanks for adding the lwc modal across the board, Josh!

**Comment by alexed1** [comment]
V 1.5.2 10/29/22 [Production](https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G0000043wsvQAA) [Sandbox](https://test.salesforce.com/packaging/installPackage.apexp?p0=04t5G0000043wsvQAA) lwc modal changes

**Comment by alexed1** [comment]
Hi Josh. Take a look at the reports at https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000JeWml  This commit is the only commit that 
Do you have any time to take a look?

**Comment by jdayment** [comment]
I can look at it this afternoon I am not sure what from my items would have
caused this let me try and duplicate it.

**Pull request merged**
