### PR TITLE
Text Area Plus June Update

### PR DESCRIPTION
**Pull request by jdayment**
Adds Text Input option and optional Help Text along with minor bug fixes

### CODE REVIEW

**Review by alexed1 — APPROVED** [review]
nice improvements, Josh!

**Comment by alexed1** [comment]
version 1.8 https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G000003zgYrQAI

**Comment by alexed1** [comment]
I've updated https://unofficialsf.com/wp-admin/post.php?post=27533&action=edit with version 1.8, but haven't changed the text of that post. Can you update with the new features?

**Comment by jdayment** [comment]
Sure thing

**Comment by ericrsmith35** [comment]
I've updated the TOC page.  https://unofficialsf.com/flow-screen-components/

**Pull request merged**
